"""Compare the engine with a real bash binary on the same scripts"""

# Standard libraries
import os
import shutil
import subprocess
from pathlib import Path

# Third-party libraries
import pytest

# Project libraries
from tests.conftest import build_harness

BASH_PATH = shutil.which("bash")
BASH_TIMEOUT_S = 30
BASH_ENVIRONMENT = {"HOME": "/h", "PATH": "/usr/bin:/bin"}

SCRIPTS = [
    "echo a  b\tc",
    "echo 'single quoted  spaces'",
    'echo "double quoted  spaces"',
    "echo mixed'quo'\"ting\"done",
    "echo \\$HOME",
    "echo '$HOME'",
    'echo "\\$x \\" \\\\ \\a"',
    "echo a\\\nb",
    "echo 'it'\\''s'",
    'echo ""',
    "echo '' ''",
    "echo $empty",
    'echo "$empty"',
    "echo x${empty}y",
    "echo a#b #comment",
    "echo \\#notcomment",
    "echo -n a; echo -n b; echo",
    "echo -e 'x\\ty'",
    "echo -E 'x\\ty'",
    "echo -ne 'x\\n'",
    "echo -- -n",
    "echo -nx",
    "echo -e 'line\\cstop'; echo after",
    "x=5; echo $x",
    "x=5 y=6; echo $x$y",
    "x='a  b'; echo $x; echo \"$x\"",
    "x='a  b'; for w in $x; do echo \"[$w]\"; done",
    "echo ${x:-default}",
    'x=; echo ${x:-default} "${x-default}"',
    "x=set; echo ${x:+alt}",
    "echo ${y:+alt}z",
    "echo ${x:=assigned}; echo $x",
    "x=hello; echo ${#x}",
    "echo $#",
    "f() { echo $# $1 $2 \"$@\"; }; f a 'b c'",
    'f() { echo "$*"; }; f a b c',
    "f() { for a; do echo $a; done; }; f x y",
    "f() { echo ${1:-none}; }; f; f given",
    "echo $0 | head -c 1 >/dev/null; echo ok",
    "false; echo $?; true; echo $?",
    "echo $?",
    "x=1; x=2 true; echo $x",
    "x=outer; f() { echo $x; }; x=inner f",
    'x="a\nb"; echo "$x"',
    "x='a*b'; echo $x",
    "echo $(echo inner)",
    'echo "$(echo a; echo b)"',
    "echo $(echo a; echo b)",
    "echo `echo tick`",
    "echo $(echo $(echo nested))",
    "x=$(echo val); echo $x",
    "x=$(printf 'a\\n\\n'); echo \"[$x]\"",
    "echo pre$(echo mid)post",
    "echo \"$(echo 'quoted inside')\"",
    "echo $(echo 'a  b')",
    "echo $(true)x",
    "echo $(false); echo $?",
    "x=$(false); echo $?",
    "echo $(echo a | head -n 1)",
    "echo $(yes | head -n 2)",
    'echo "$(yes | head -n 2)"',
    "echo a | cat",
    "echo a | cat | cat | cat",
    "yes | head -n 3",
    "yes | head -n 1 | cat",
    "yes abc | head -n 2",
    "yes | head -c 4",
    "echo a | head -n 0; echo $?",
    "echo a | true; echo $?",
    "true | false; echo $?",
    "false | true; echo $?",
    "! true; echo $?",
    "! false; echo $?",
    "! echo a | cat; echo $?",
    "! false | cat; echo $?",
    "echo a | echo b",
    "yes | echo done",
    "printf 'a\\nb\\nc\\n' | head -n 2",
    "printf 'a\\nb\\nc' | cat",
    "printf 'no newline' | head -n 1",
    "printf 'a\\nb\\n' | cat -n",
    "echo a | cat - ",
    "(echo a; echo b) | head -n 1",
    "{ echo a; echo b; } | cat",
    "echo piped | { cat; }",
    "echo piped | (cat)",
    "if true; then echo x; fi | cat",
    "for i in 1 2; do echo $i; done | head -n 1",
    "while true; do echo loop; break; done | cat",
    "f() { echo fn; }; f | cat",
    "true && echo yes",
    "false && echo yes; echo $?",
    "false || echo no",
    "true || echo no; echo $?",
    "true && false || echo c",
    "false || false || echo last",
    "true && echo a && echo b",
    "echo a | cat && echo b | cat",
    "false && echo a || echo b | cat",
    "true && { echo grp; }",
    "false || (echo sub)",
    "true && ! false && echo both",
    "x=1 && echo $x",
    "false; true && echo $?",
    "true;false;echo $?",
    "echo a;;echo b",
    "echo a ; echo b ;",
    "if true; then echo a; fi",
    "if false; then echo a; fi; echo $?",
    "if false; then echo a; else echo b; fi",
    "if false; then echo a; elif true; then echo b; else echo c; fi",
    "if false; then echo a; elif false; then echo b; else echo c; fi",
    "if true\nthen\n echo multi\nfi",
    "if echo cond; then echo body; fi",
    "if false; then echo a; fi; echo after",
    "if true; then if false; then echo i; else echo n; fi; fi",
    "if true; then false; fi; echo $?",
    "if ! false; then echo neg; fi",
    "if true && false; then echo a; else echo b; fi",
    "if echo a | cat; then echo piped; fi",
    "for i in 1 2 3; do echo $i; done",
    "for i in 1 2 3; do echo $i; break; done",
    "for i in 1 2 3; do continue; echo $i; done; echo end",
    "for i in; do echo $i; done; echo none",
    "for i in a; do echo $i; done; echo $i",
    "for i in $(echo a b); do echo $i; done",
    'for i in "$(echo a b)"; do echo $i; done',
    "for i in 1 2\ndo\n echo $i\ndone",
    "for i in 1 2; do for j in a b; do echo $i$j; done; done",
    "for i in 1 2; do for j in a b; do break; done; echo $i; done",
    "for i in 1 2 3; do if true; then break; fi; echo $i; done",
    "for i in 1 2 3; do false; done; echo $?",
    "for i in 1 2 3; do true; done; echo $?",
    "n=0; while true; do echo $n; break; done",
    "while false; do echo never; done; echo $?",
    "until true; do echo never; done; echo done",
    "until false; do echo once; break; done",
    "while true; do if true; then break; fi; done; echo out",
    "while true\ndo\n break\ndone\necho ok",
    "i=0; while true; do i=1; break; done; echo $i",
    "f() { echo hi; }; f",
    "f() { echo hi $1; }; f bob",
    "function f { echo kw; }; f",
    "function f() { echo kw2; }; f",
    "f() ( echo sub ); f",
    "f() { return 3; }; f; echo $?",
    "f() { echo a; return; echo b; }; f",
    "f() { false; }; f; echo $?",
    "f() { true; }; f; echo $?",
    "f() { x=changed; }; x=orig; f; echo $x",
    "f() ( x=changed ); x=orig; f; echo $x",
    "f() { g; }; g() { echo inner; }; f",
    'f() { echo $1; }; g() { f "$@"; }; g passed',
    "f() { echo one; }; f() { echo two; }; f",
    "f() {\n echo multi\n echo line\n}\nf",
    "f() { for i in 1 2; do return 5; done; }; f; echo $?",
    "f() { while true; do return 7; done; }; f; echo $?",
    "f() { echo $#; }; f; f a; f a b",
    "unset -f f 2>/dev/null; f() { echo new; }; f",
    "(echo a; echo b)",
    '(x=1); echo "[$x]"',
    "x=1; (x=2; echo $x); echo $x",
    "(exit 3); echo $?",
    "(false); echo $?",
    "{ echo a; echo b; }",
    "{ x=1; }; echo $x",
    "{ false; }; echo $?",
    "( ( echo nested ) )",
    "{ { echo nested; }; }",
    "(echo a) && echo b",
    "{ echo a; } && echo b",
    "( echo a | cat ) | cat",
    "x=1; { x=2; (x=3); echo $x; }",
    "exit 3",
    "echo a; exit 4; echo b",
    "exit",
    "false; exit",
    "(exit 5); echo $?",
    "f() { exit 6; }; f; echo after",
    "for i in 1 2; do exit 2; done; echo after",
    "echo before | cat; exit 1",
    "export A=1; echo $A",
    "export A=1 B=2; echo $A$B",
    'A=1; unset A; echo "[$A]"',
    ":; echo $?",
    ": ignored args; echo ok",
    "break; echo after",
    "continue; echo after",
    "return; echo after",
    "f() { break; echo after-break; }; for i in 1 2; do f; echo loop; done",
    "echo a > out; cat out",
    "echo a > out; echo b > out; cat out",
    "echo a > out; echo b >> out; cat out",
    "echo a >out; cat <out",
    "echo a > out; cat < out | cat",
    "printf 'x\\ny\\n' > out; head -n 1 < out",
    "{ echo a; echo b; } > out; cat out",
    "(echo a; echo b) > out; cat out",
    "for i in 1 2; do echo $i; done > out; cat out",
    "echo a > out 2>&1; cat out",
    "cat missing 2> err; echo $?; cat err | head -c 3",
    "cat missing 2>/dev/null; echo $?",
    "cat missing 2>&1 | head -c 3",
    "cat missing >/dev/null 2>&1; echo $?",
    "cat missing &> both; head -c 3 both",
    "echo a 1> out; cat out",
    "echo 2 > out; cat out",
    "echo a>out; cat out",
    "echo a >'quoted name'; cat 'quoted name'",
    "n=out; echo a > $n; cat $n",
    "echo a > out; echo b > out2; cat out out2",
    "cat < missing; echo $?",
    "echo a > out; cat out out",
    "echo >out; cat out | head -c 1 | cat -n",
    "cat <<EOF\nhello\nEOF",
    "x=7; cat <<EOF\nvalue $x\nEOF",
    "x=7; cat <<'EOF'\nraw $x\nEOF",
    'x=7; cat <<"EOF"\nraw $x\nEOF',
    "cat <<-EOF\n\tindented\n\tEOF",
    "cat <<EOF\na\nb\nEOF\necho after",
    "cat <<EOF | head -n 1\nfirst\nsecond\nEOF",
    "cat <<EOF | cat | cat\nthrough\nEOF",
    "cat <<EOF > out\nfiled\nEOF\ncat out",
    "cat <<EOF\n$(echo sub)\nEOF",
    "cat <<EOF\n\\$escaped\nEOF",
    "cat <<EOF\n`echo tick`\nEOF",
    "cat <<A <<B\n1\nA\n2\nB",
    "if true; then cat <<EOF\ninside\nEOF\nfi",
    "f() { cat <<EOF\nin fn\nEOF\n}; f",
    "cat <<< 'here string'",
    'x=word; cat <<< "$x here"',
    "cat <<< $(echo sub)",
    "head -n 1 <<EOF\n1\n2\nEOF",
    "cat <<EOF\nEOF\necho empty",
    "cat <<EOF\n  leading spaces\nEOF",
    "printf 'a\\nb\\n' > f1; printf 'c\\n' > f2; cat f1 f2",
    "printf 'a\\nb\\n' > f1; echo p | cat f1 - f1",
    "printf 'a\\nb\\n' > f1; cat -n f1",
    "cat missing f1 2>/dev/null; echo $?",
    "cat nothing_here 2>/dev/null; echo $?",
    "printf '1\\n2\\n3\\n' > f; head -n 2 f",
    "printf '1\\n2\\n3\\n' > f; head -2 f",
    "printf '1\\n2\\n3\\n' > f; head -n 5 f",
    "printf '1\\n2\\n3\\n' > f; head -c 2 f",
    "printf '1\\n2\\n3\\n' > f; head -n 0 f; echo $?",
    "printf '1\\n' > a; printf '2\\n' > b; head a b",
    "printf '1\\n' > a; printf '2\\n' > b; head -q a b",
    "printf '1\\n' > a; head -v a",
    "head missing 2>/dev/null; echo $?",
    "printf '1\\n' > a; head missing a 2>/dev/null; echo $?",
    "yes a b | head -n 1",
    "yes '' | head -n 2 | cat -n",
    "nosuchcmd; echo $?",
    "nosuchcmd 2>/dev/null; echo $?",
    "nosuchcmd | cat; echo $?",
    "echo a | nosuchcmd; echo $?",
    "nosuchcmd && echo a || echo b",
    "if nosuchcmd 2>/dev/null; then echo a; else echo b; fi",
    'x=$(nosuchcmd 2>/dev/null); echo "[$x]" $?',
    "echo a;echo b",
    "echo a\n\n\necho b",
    "   echo   spaced   ",
    "echo a # comment ; echo b",
    "echo 'a;b'",
    'echo "a|b"',
    "echo 'a&&b'",
    "echo a\\;b",
    "echo a \\| b",
    "echo '('",
    "echo ')'",
    "echo '{'",
    "echo }",
    "echo a{b",
    "echo if then fi",
    "echo for do done",
    "echo done; echo fi; echo esac",
    "x=fi; echo $x",
    "echo \\\\",
    "echo '\\'",
    'echo "\\\\"',
    "HOME=/h; echo ~ ~/x '~' a~",
    "echo $",
    "echo $$ | head -c 0; echo ok",
    "echo a$",
    "echo '$'",
    'echo "$"',
    "echo ${}; echo $?",
    "echo $(echo $(echo $(echo $(echo deep))))",
    "f() { if true; then for i in 1; do while true; do echo deep; break; done; done; fi; }; f",
    "( ( ( echo three ) ) )",
    "{ { { echo three; }; }; }",
    "for i in 1 2 3 4 5 6 7 8 9 10; do echo $i; done | head -n 3",
    "i=0; for a in 1 2 3; do for b in 1 2 3; do for c in 1 2 3; do echo $a$b$c; done; done; done | head -n 2",
    "yes | head -n 10000 | head -n 1",
    "yes | head -n 2000 | cat | cat | cat | head -n 1",
    "for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do echo $i; done | head -n 3",
    "f() { echo $1; }; for i in 1 2 3 4 5 6 7 8 9 10; do f $i; done | cat -n | head -n 2",
    "x=''; for i in 1 2 3 4 5 6 7 8 9 10; do x=\"$x$i\"; done; echo $x",
    "yes | head -c 100000 | head -c 3",
    "printf '%s\\n' a b c d e f g h i j k l m n o p q r s t u v w x y z | head -n 26 | head -n 2",
    "printf 'plain\\n'",
    "printf '%s %s\\n' a b",
    "printf '%s\\n' a b c",
    "printf '%s-%s\\n' a b c",
    "printf '%d\\n' 42",
    "printf '%5d|%-5d|%05d\\n' 42 42 42",
    "printf '%x %X %o\\n' 255 255 8",
    "printf '%.2f\\n' 3.14159",
    "printf '%s\\n'",
    "printf '%d\\n'",
    "printf 'no newline'",
    "printf '%%\\n'",
    "printf 'tab\\there\\n'",
    "printf '%b\\n' 'esc\\tin arg'",
    "printf '%s\\n' 'no\\tesc in s'",
    "printf '%c\\n' hello",
    "printf '%5s|%-5s|\\n' ab ab",
    "printf '%.2s\\n' abcdef",
    "printf '%d\\n' notnum 2>/dev/null; echo $?",
    "printf '%d %s\\n' 1 a 2 b",
    "printf -- '-dash\\n'",
    "printf '%s\\n' \"$(printf 'a\\nb')\"",
    "printf '\\101\\x42\\n'",
    "printf '%*d|\\n' 4 7",
    "printf '%q\\n' 'a b'",
    "printf '%q\\n' plain",
    "printf '%u\\n' 5",
    "printf '%i\\n' 0x10",
    "printf '%e\\n' 1234.5",
    "printf '%g\\n' 0.0001",
    "printf '%d\\n' \"'A\"",
    "printf 'x' >out; printf 'y' >>out; cat out; echo",
    "echo \"nested 'single' inside\"",
    "echo 'nested \"double\" inside'",
    'echo "a\\"b"',
    "echo 'a'\\''b'",
    'echo "\\`not sub\\`"',
    "echo '`not sub`'",
    'echo "$(echo "inner \\"q\\"")"',
    "echo \"$(echo 'single in sub')\"",
    'echo $(echo "double in sub")',
    "echo \"${x:-'literal quotes'}\"",
    'echo ${x:-"a b"}',
    'x=\'a"b\'; echo "$x"',
    'echo "multi\nline"',
    "echo 'multi\nline'",
    'echo "a\\\nb"',
    "echo 'a\\\nb'",
    'echo "\\\\n"',
    "echo 'back\\slash'",
    'echo "back\\slash"',
    "echo a\\ \\ b",
    'echo "$x""$y"end',
    "echo ''\"\"''",
    'echo """"',
    "echo '$(echo not)'",
    'echo "\\$(echo not)"',
    "echo \\$(echo not)",
    'echo "${unset}"end',
    'echo x"${unset}"y',
    "x=echo; $x hi",
    "x='echo hi'; $x",
    "x=' a b '; echo \"[$x]\"",
    "x=' a b '; echo [$x]",
    'x=a; y=b; echo $x$y ${x}${y} "$x$y"',
    'x=5; echo "${x}px" ${x}px $x.px',
    "x=5; echo ${#x} ${#unset}",
    "x='  '; echo \"[$x]\" [$x]",
    "x='*'; echo \"$x\"",
    "echo ${1:-no args}",
    "f() { echo ${2:-second missing}; }; f one",
    'f() { echo "$1" "$2"; }; f \'a b\' c',
    'f() { for w in "$@"; do echo "[$w]"; done; }; f \'a b\' c',
    "f() { for w in $@; do echo \"[$w]\"; done; }; f 'a b' c",
    'f() { for w in "$*"; do echo "[$w]"; done; }; f \'a b\' c',
    'f() { echo $#; }; f "" ""',
    "f() { echo $#; }; f $empty",
    'f() { echo $#; }; f "$empty"',
    "echo $(echo $(echo $(echo a) b) c)",
    'echo "$(echo "$(echo "deep")")"',
    'x=$(echo a; echo b); echo "$x"',
    "x=$(echo a; echo b); echo $x",
    "x=`echo back`; echo $x",
    'x=$(echo); echo "[$x]"',
    "x=$(printf ''); echo \"[$x]\"",
    "x=$(printf 'a\\n\\n\\n'); echo \"[$x]\"",
    "x=$(printf '\\n\\na'); echo \"[$x]\"",
    "echo $(echo '  spaced  ')",
    "echo \"$(echo '  spaced  ')\"",
    "cat <<EOF\n$(echo one; echo two)\nEOF",
    "cat <<EOF\n\"quotes stay\" 'here'\nEOF",
    "x=1; cat <<EOF\n${x}0 ${y:-def}\nEOF",
    "cat <<EOF\n\\\\ \\$ \\`\nEOF",
    "if false; then :; fi; echo $?",
    "if false; then :; else false; fi; echo $?",
    "for i in 1; do false; done; echo $?",
    "for i in; do false; done; echo $?",
    "while false; do :; done; echo $?",
    "until true; do :; done; echo $?",
    "f() { false; true; }; f; echo $?",
    "f() { return 300; }; f; echo $?",
    "(exit 256); echo $?",
    "exit 257",
    "(false; echo $?)",
    "echo a | false; echo $?",
    "false | echo a; echo $?",
    "! false | false; echo $?",
    "true && false; echo $?",
    "false || false; echo $?",
    "false; (echo $?)",
    "false; { echo $?; }",
    "false; echo $? $?",
    "false; x=$?; echo $x",
    "false; f() { echo $?; }; f",
    "false; if true; then echo $?; fi",
    "false; for i in 1; do echo $?; done",
    "x=$(false) y=$(true); echo $?",
    "x=$(true) y=$(false); echo $?",
    "true; x=1; echo $?",
    "false; x=1; echo $?",
    "nosuch 2>/dev/null; x=1; echo $?",
    "echo a > out; echo b >> out; echo c > out; cat out",
    "echo a > out1 > out2; cat out2; cat out1; echo $?",
    "echo a >> new; cat new",
    "cat < missing 2>/dev/null; echo $?",
    "echo a > out; cat <out <out",
    "echo a > 'sp ace'; cat 'sp ace' \"sp ace\"",
    'x=out; echo a >"$x"; cat $x',
    "echo a > out; cat out > copy; cat copy",
    "echo a | cat > out; cat out",
    "echo a > out | cat; echo end",
    "cat missing 2>&1 >/dev/null; echo $?",
    "cat missing 2>/dev/null | cat; echo $?",
    "{ echo a; cat missing; } 2>&1 | head -n 1",
    "{ echo a; cat missing; } 2>/dev/null; echo $?",
    "(cat missing) 2>/dev/null; echo $?",
    "if cat missing 2>/dev/null; then echo a; else echo b; fi",
    "for i in 1 2; do echo $i; done > out; head -n 1 < out",
    "while true; do echo loop; break; done > out; cat out",
    "if true; then echo a; fi > out; cat out",
    "f() { echo fn; }; f > out; cat out",
    "f() { echo fn; cat missing; }; f 2>/dev/null; echo $?",
    "f() { cat; }; echo in | f",
    "f() { cat; }; f < /dev/null; echo end",
    "cat /dev/null; echo $?",
    "echo a > /dev/null; echo $?",
    "echo a >> /dev/null; echo b",
    "yes | head -n 100 > /dev/null; echo done",
    "echo a 2>&1 | cat",
    "echo\ta\tb",
    "echo a ;echo b ; echo c",
    "echo a|cat",
    "echo a|cat|cat",
    "echo a&&echo b",
    "echo a||echo b",
    "true&&echo b",
    "echo a   |   cat",
    "if true;then echo a;fi",
    "for i in 1 2;do echo $i;done",
    "while true;do break;done;echo ok",
    "f(){ echo compact; };f",
    "f() {\necho a\n}\nf",
    "{ echo a;}",
    "( echo a )",
    "(echo a)|cat",
    "{ echo a; }|cat",
    "echo a # trailing comment",
    "#!/bin/bash\necho shebang",
    "echo a\n# comment line\necho b",
    "echo a \\\n  b \\\n  c",
    "echo a |\\\ncat",
    "echo a &&\\\necho b",
    "\n\n\necho after blanks\n\n",
    "   ",
    "",
    "# only comment",
    "echo a;",
    "echo if",
    "echo then",
    "echo else",
    "echo elif",
    "echo while",
    "echo until",
    "echo for",
    "echo in",
    "echo function",
    "echo select",
    "echo case",
    "echo esac",
    "echo '{' '}' '(' ')'",
    "echo \\{ \\}",
    "echo '!'",
    "echo \\!",
    "x=if; echo $x",
    "for if in 1; do echo $if; done",
    "if echo if; then echo then; fi",
    "echo do done",
    "f() { x=1; }; f; echo $x",
    "x=0; f() { x=1; }; f; echo $x",
    "f() { f2() { echo inner-def; }; }; f; f2",
    'f() { echo "$1"; }; f "$(echo sub arg)"',
    "f() { echo $1; }; f $(echo a b)",
    "f() { echo $#; }; f $(echo a b)",
    "f() { return; }; false; f; echo $?",
    "f() { return $?; }; false; f; echo $?",
    "f() { return 1; }; if f; then echo yes; else echo no; fi",
    "f() { true; }; while f; do echo once; break; done",
    "f() { echo $1; }; for i in a b; do f $i; done",
    "f() { for i in 1 2; do echo $i; done; }; f; f",
    "f() { echo a; }; g() { f; echo b; }; g",
    "f() { g; }; g() { echo late; }; f",
    "f() { echo one; }; x=$(f); echo $x",
    "f() { cat; }; f <<EOF\nheredoc to fn\nEOF",
    'f() { echo "$@"; }; f a   b',
    'f() { unset x; }; x=1; f; echo "[$x]"',
    "f() { x=in; echo $x; }; x=out; f; echo $x",
    "x=out; f() { echo $x; }; (x=sub; f); f",
    "f() { exit 3; }; (f); echo $?",
    "f() { exit 3; }; x=$(f); echo $?",
    "f() { break; }; for i in 1 2; do f 2>/dev/null; echo $i; done",
    "for i in 1 2; do f() { echo $i; }; done; f",
    "for i in 1 2 3; do for j in a b; do if true; then continue; fi; echo $i$j; done; done; echo end",
    "for i in 1 2 3; do for j in a b; do break; done; done; echo end",
    "for i in 1 2; do while true; do break; done; echo $i; done",
    "while true; do for i in 1; do break; done; break; done; echo ok",
    "for i in 1 2; do (break); echo $i; done",
    "for i in 1 2; do { break; }; echo $i; done",
    "for i in 1 2; do if true; then continue; fi; echo $i; done",
    "for i in 1 2; do echo $i | cat; done",
    "for i in 1 2; do echo $i; done | for j in a; do cat; done",
    "i=0; while true; do i=x$i; echo $i; if true; then break; fi; done",
    "until false; do echo a; break; done; until false; do echo b; break; done",
    "for i in 'a b' c; do echo \"$i\"; done",
    'for i in "a b" c; do echo $i; done',
    "for i in $(echo 'a b') c; do echo $i; done",
    "for i in a\\ b c; do echo $i; done",
    "for i in a; do echo $i; done; for i in b; do echo $i; done",
    "for i in 1 2 3; do echo $i; break; echo after; done; echo $i",
    "for i in a b c; do echo $i; done > out; for j in $(cat out); do echo [$j]; done",
    "for i in $(yes | head -n 3); do echo $i; done",
    "if true; then :; elif true; then echo no; fi; echo ok",
    "if false; then :; elif false; then :; fi; echo $?",
    "if false; then :; elif false; then :; else echo e; fi",
    "if true; then\necho a\nelse\necho b\nfi",
    "if true\nthen echo a\nfi",
    "if\ntrue\nthen\necho a\nfi",
    "if true; then echo a; fi; if false; then echo b; fi; echo c",
    "if false; true; then echo list; fi",
    "if true; false; then echo yes; else echo no; fi",
    "if echo a | cat; then echo b; fi",
    "if ! echo a | cat; then echo b; else echo c; fi",
    "if (false); then echo a; else echo b; fi",
    "if { true; }; then echo a; fi",
    "if x=1; then echo $x; fi",
    "if true; then if true; then if true; then echo three; fi; fi; fi",
    "if true; then for i in 1 2; do echo $i; done; fi",
    "if true; then while true; do echo w; break; done; fi",
    "if true; then f() { echo infn; }; fi; f",
    "if true; then echo a; fi | cat",
    "if true; then echo a; fi && echo b",
    "if false; then echo a; fi || echo b",
    "if true; then echo a; fi; echo $?",
    "if true; then cat; fi <<EOF\nfed\nEOF",
    "echo in | if true; then cat; fi",
    '(x=1; echo $x); echo "[$x]"',
    "x=1; (x=2); echo $x",
    "x=1; { x=2; }; echo $x",
    "(f() { echo infn; }); f 2>/dev/null; echo $?",
    "{ f() { echo infn; }; }; f",
    "(echo a; false); echo $?",
    "(echo a; false) | cat; echo $?",
    "{ echo a; false; } | cat; echo $?",
    "(exit 1) || echo b",
    "{ false; } || echo b",
    "( (false) ); echo $?",
    "(true) && (echo a)",
    "x=$( (echo sub) ); echo $x",
    "x=$({ echo grp; }); echo $x",
    "( echo a\necho b )",
    "{\necho a\necho b\n}",
    "(\necho a\n)",
    "( echo a ) > out; cat out",
    "( echo a ) 2>/dev/null; echo $?",
    "echo in | ( cat )",
    "echo in | { cat; cat; }",
    "echo in | ( cat; echo after )",
    "( yes | head -n 2 )",
    "{ yes | head -n 2; }",
    "x=1; ( x=2; ( x=3; echo $x ); echo $x ); echo $x",
    "(exit 2) ; echo $?",
    "(exit) ; echo $?",
    "false; (exit); echo $?",
    "false; ( : ); echo $?",
    "(echo $?)",
    "{ echo a; } > out 2>&1; cat out",
    "{ cat missing; } > out 2>&1; head -c 3 out",
]


def run_real_bash(script: str, cwd: Path) -> tuple[str, int]:
    """Return what the real bash prints and exits with for a script

    Args:
        script: The script text
        cwd: An empty directory to run in

    Returns:
        Standard output and the exit code
    """
    completed = subprocess.run(
        [BASH_PATH or "bash", "-c", script],
        cwd=cwd,
        env={**BASH_ENVIRONMENT, "SYSTEMROOT": os.environ.get("SYSTEMROOT", "")},
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=BASH_TIMEOUT_S,
    )
    return completed.stdout, completed.returncode


@pytest.mark.live_bash_test
@pytest.mark.skipif(BASH_PATH is None, reason="needs a bash binary on PATH")
@pytest.mark.parametrize("script", SCRIPTS, ids=[f"script_{index}" for index in range(len(SCRIPTS))])
def test_engine_matches_real_bash(script: str, tmp_path: Path) -> None:
    """Check that the engine prints the same standard output and exit code as bash for one script"""
    bash_directory = tmp_path / "bash"
    engine_directory = tmp_path / "engine"
    bash_directory.mkdir()
    engine_directory.mkdir()
    shell = build_harness(engine_directory)
    shell.state.variables["HOME"] = BASH_ENVIRONMENT["HOME"]

    expected_stdout, expected_exit_code = run_real_bash(script, bash_directory)
    run = shell.run(script)

    assert (run.stdout, run.exit_code) == (expected_stdout, expected_exit_code)
